language: r
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      sudo: required

before_install:
    - sudo apt-get install libpoppler-cpp-dev

script:
    - Rscript $TRAVIS_BUILD_DIR/src/crawler.R
    - cd $TRAVIS_BUILD_DIR/src/ &&  Rscript $TRAVIS_BUILD_DIR/src/parser.R & cd $TRAVIS_BUILD_DIR

addons:
    apt:
        packages:
            - libwebp-dev
            - libpoppler-cpp-dev

after_success:
    - if [[ "${R_CODECOV}" ]]; then Rscript -e 'covr::codecov()'; fi

notifications:
    email:
        on_success: always
        on_failure: always
