language: r
sudo: false
cache: packages


before_install:

script:
    - Rscript $TRAVIS_BUILD_DIR/src/crawler.R
    - cd $TRAVIS_BUILD_DIR/src/ &&  Rscript $TRAVIS_BUILD_DIR/src/parser.R & cd $TRAVIS_BUILD_DIR

